name: CI-CD_Media_Streaming
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.STORAGE_NAME }} \
              --account-key ${{ secrets.STORAGE_KEY }} \
              --destination '$web' \
              --source . \
              --pattern "index.html" \
              --overwrite
